f1/urls.py
from django.urls import path, include

from . import views
app_name = 'f1'
urlpatterns = [
    path('',views.a, name='f1')
]

f2/urls.py
from django.urls import path, include

from . import views
app_name = 'f2'
urlpatterns = [
    path('',views.b, name='f2')
]

f3/urls.py
from django.urls import path, include

from . import views
app_name = 'f3'
urlpatterns = [
    path('',views.c, name='f3')
]

f4/urls.py
from django.urls import path, include

from . import views
app_name = 'f4'
urlpatterns = [
    path('', views.d, name='f4')
    ]

school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("f1.urls")),
    path('f2/', include("f2.urls")),
    path('f3/', include("f3.urls")),
    path('f4/', include("f4.urls"))
]

f1/models.py
from django.db import models

# Create your models here.

f2/models.py
from django.db import models

# Create your models here.

f3/models.py
from django.db import models

# Create your models here.

f4/models.py
from django.db import models

# Create your models here.

f1/views.py
from django.shortcuts import render











# Create your views here.
def a(request):
    return render(request,'f1.html')

f2/views.py
from django.shortcuts import render

# Create your views here.
def b(request):
    return render(request,'f2.html')

f3/views.py
from django.shortcuts import render

# Create your views here.
def c(request):
    return render(request,'f3.html')

f4/views.py
from django.shortcuts import render

# Create your views here.
def d(request):
    return render(request,'f4.html')

f1/templates/f1.html
{% extends 'layout.html' %}



{% block body %}
<p class="j"> welcome to form 1</p>

{%  endblock %}

f1/templates/f2.html
{% extends 'layout.html' %}



{% block body %}
<p class="j">welcome to form 2</p>

{%  endblock %}

f1/templates/f3.html
{% extends 'layout.html' %}


{% block body %}


<p>welcome to form 3</p>

{%  endblock %}

f1/templates/f4.html
{% extends 'layout.html' %}



{% block body %}
<p>welcome to form 4</p>

{%  endblock %}

f1/templates/layout.html
{%  load static %}


<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <title>Document</title>

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
</head>
<body>
<div class="row">
    <div class="col-md-3">
        <a class="one" href="{%  url 'f1:f1' %}"> <button class="one">FORM 1</button> </a>

    </div>
    <div class=" col-md-3">
        <a href="{% url 'f2:f2' %}"> <button class="two">FORM 2</button></a>
    </div>
    <div class="col-md-3">

        <a href="{% url 'f3:f3' %}"> <button class="three">FORM 3</button></a>
    </div>
    <div class="col-md-3">

        <a href="{% url 'f4:f4' %}"> <button class="four">FORM 4</button> </a>
    </div>





</div>

{% block body %}


{%  endblock %}









</body>
</html>